- type: antag
  id: Fugitive
  name: roles-antag-fugitive-name
  antagonist: true
  objective: roles-antag-fugitive-objective
  # keep these in sync with the spawner
  requirements:
    - !type:OverallPlaytimeRequirement # NS - Add overall playtime requirement
      time: 7200 # NS - 2 hours

- type: startingGear
  id: FugitiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackFilled
    shoes: ClothingShoesChameleonNoSlips
    id: PassengerPDA
  #innerClothingSkirt: ClothingUniformJumpskirtPrisoner # FIXME doesnt work
  inhand:
  - ToolboxElectricalFilled
  storage:
    back:
    - FugitiveStash
