- type: antag
  id: ListeningPost
  name: roles-antag-listening-post-name
  antagonist: true
  objective: roles-antag-listening-post-objective
  # keep these in sync with the spawner
  requirements: # Worth considering these numbers for the goal of making sure someone willing to MRP takes this.
  - !type:OverallPlaytimeRequirement
    time: 7200 # NS - 2 hours
