using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NS.Consent.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ConsentEditor : Control
    {
        public Action<string>? OnConsentTextChanged;

        public ConsentEditor()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CConsentEditorInput.Placeholder = new Rope.Leaf(loc.GetString("consent-window-text"));
            CConsentEditorInput.OnTextChanged += _ => FlavorTextChanged();
        }

        public void FlavorTextChanged()
        {
            OnConsentTextChanged?.Invoke(GetText());
        }

        public string GetText()
        {
            return Rope.Collapse(CConsentEditorInput.TextRope).Trim();
        }
    }
}
