- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
#  whitelistRequired: true
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security

- type: startingGear
  id: PrisonerGear
  equipment:
    id: PrisonerPDA
    ears: ClothingHeadsetPrison
