- type: job
  id: ChiefJustice
  name: job-name-chief-justice
  description: job-description-chief-justice
  playTimeTracker: JobChiefJustice
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600 # Nebulous - 6 hours
  weight: 20
  startingGear: CJGear
  icon: "JobIconChiefJustice"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - ChiefJustice
  - Justice
  - Lawyer
  - Prosecutor
  - Clerk
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: CJGear
  equipment:
    #jumpsuit: ClothingUniformJumpsuitChiefJustice
    #back: ClothingBackpackFilled # TODO- make Justice department bags
    #shoes: ClothingShoesLeather
    #head: ClothingHeadHatCJToque
    #outerClothing: ClothingOuterChiefJustice
    id: ChiefJusticePDA
    ears: ClothingHeadsetAltJustice
    #gloves: ClothingHandsGlovesColorWhite
    # Todo - pocket1: Gavel
    #innerClothingSkirt: ClothingUniformJumpskirtChiefJustice
    #satchel: ClothingBackpackSatchelFilled # TODO- make Justice departmebt bags
    #duffelbag: ClothingBackpackDuffelFilled


