- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # NS - 2 hrs
  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Clerk
  - Maintenance

- type: startingGear
  id: ClerkGear
  equipment:
    #jumpsuit: ClothingUniformJumpsuitClerk
    #back: ClothingBackpackFilled
    #shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
    #innerClothingSkirt: ClothingUniformJumpskirtClerk
    #satchel: ClothingBackpackSatchelFilled
    #duffelbag: ClothingBackpackDuffelFilled


