- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 4 # DeltaV - Reduced TC: Security Radio and Access
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj  # Delta V - Change supervisor to chief justice
  access:
  # - Service - DeltaV, removed from service department
  - Justice # DeltaV - Justice dept
  - Lawyer
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetJustice # DeltaV - Added lawyer to justice department
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
